# Generated by Django 5.1.6 on 2025-03-03 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20250303_1443'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
